name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Build
      run: go build -v ./...
  
    - name: Build and publish image to Quay
      uses: docker/build-push-action@v1
      with:
        path: .
        registry: ${{ secrets.REGISTRY_URI }}
        repository: ${{ secrets.REGISTRY_USERNAME }}/${{ secrets.REGISTRY_REPO }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        tags: "v4.0.0"
